// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDur9nYAxVkwmq29S_JVQBWiu7MCLzONeU',
    appId: '1:895373216385:web:b20fd8a8e1e0e9ddb79b80',
    messagingSenderId: '895373216385',
    projectId: 'appartmentapp-d387f',
    authDomain: 'appartmentapp-d387f.firebaseapp.com',
    storageBucket: 'appartmentapp-d387f.appspot.com',
    measurementId: 'G-WBM51M6WM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0mWnICgLoGDv1qvmvOFkynGo2o_hUdfo',
    appId: '1:895373216385:android:a6ec4eee0c89b36db79b80',
    messagingSenderId: '895373216385',
    projectId: 'appartmentapp-d387f',
    storageBucket: 'appartmentapp-d387f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqKvPaXP4DEB6GzOVWynRe59fY2B9wou0',
    appId: '1:895373216385:ios:5c980af456a5c11bb79b80',
    messagingSenderId: '895373216385',
    projectId: 'appartmentapp-d387f',
    storageBucket: 'appartmentapp-d387f.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqKvPaXP4DEB6GzOVWynRe59fY2B9wou0',
    appId: '1:895373216385:ios:5c980af456a5c11bb79b80',
    messagingSenderId: '895373216385',
    projectId: 'appartmentapp-d387f',
    storageBucket: 'appartmentapp-d387f.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDur9nYAxVkwmq29S_JVQBWiu7MCLzONeU',
    appId: '1:895373216385:web:70d9df10544cb091b79b80',
    messagingSenderId: '895373216385',
    projectId: 'appartmentapp-d387f',
    authDomain: 'appartmentapp-d387f.firebaseapp.com',
    storageBucket: 'appartmentapp-d387f.appspot.com',
    measurementId: 'G-FRNGF5N0GP',
  );
}
